name: Build and deploy ASP.Net Core app to Azure Web App - UKParliamentEndPointsAIChat

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore UKParliamentEndPointsAIChat.Ui.csproj

      - name: Build with dotnet
        run: dotnet build UKParliamentEndPointsAIChat.Ui.csproj --configuration Release

      - name: Publish with dotnet
        run: dotnet publish UKParliamentEndPointsAIChat.Ui.csproj --configuration Release --output ${{ github.workspace }}/publish

      - name: List publish directory
        run: dir ${{ github.workspace }}\publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0EB5CE2799D0474CACC000A2D10CDC47 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3A493BF11BA44AEE8854F6A9F26075CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FB76509B6F3C463DB59F64F8AB46048B }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'UKParliamentEndPointsAIChat'
          package: ${{ github.workspace }}/publish
